# -*- coding: utf-8 -*-
"""Create content-addressed, non-overwriting preregistration/split freeze artifacts."""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from validate_external_preregistration import validate_preregistration


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def freeze(manifest_path: Path, prereg_path: Path, output_dir: Path, frozen_by: str) -> dict:
    manifest_bytes = manifest_path.read_bytes()
    prereg_bytes = prereg_path.read_bytes()
    manifest = json.loads(manifest_bytes)
    prereg = json.loads(prereg_bytes)
    prereg_check = validate_preregistration(prereg, require_frozen=True)
    if not prereg_check['valid']:
        raise ValueError(f'preregistration is not freeze-ready: {prereg_check["errors"]}')
    manifest_sites = sorted(map(str, manifest.get('external_sites') or []))
    prereg_sites = sorted(map(str, prereg['population'].get('external_site_ids') or []))
    if manifest_sites != prereg_sites:
        raise ValueError(f'external sites differ: manifest={manifest_sites}, preregistration={prereg_sites}')
    if not manifest.get('leakage_check_passed') or manifest.get('overlaps'):
        raise ValueError('manifest leakage check is not passed')
    manifest_hash, prereg_hash = sha256_bytes(manifest_bytes), sha256_bytes(prereg_bytes)
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_snapshot = output_dir / f'split-manifest.{manifest_hash}.json'
    prereg_snapshot = output_dir / f'preregistration.{prereg_hash}.json'
    record_path = output_dir / 'freeze-record.json'
    for path in (manifest_snapshot, prereg_snapshot, record_path):
        if path.exists():
            raise FileExistsError(f'freeze output already exists and will not be overwritten: {path}')
    manifest_snapshot.write_bytes(manifest_bytes)
    prereg_snapshot.write_bytes(prereg_bytes)
    record = {
        'schema_version': 'curve-external-freeze.v1',
        'frozen_at_utc': datetime.now(timezone.utc).isoformat(),
        'frozen_by': frozen_by,
        'attestation': 'Study team attested in the preregistration that external results were unseen at freeze time.',
        'manifest_sha256': manifest_hash,
        'preregistration_sha256': prereg_hash,
        'dataset_sha256': manifest.get('dataset_sha256'),
        'external_sites': manifest_sites,
        'manifest_snapshot': manifest_snapshot.name,
        'preregistration_snapshot': prereg_snapshot.name,
    }
    record_path.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding='utf-8')
    return {'record': str(record_path.resolve()), **record}


def validate_freeze(record_path: Path, manifest_path: Path, prereg_path: Path, dataset_path: Path | None = None) -> dict:
    record = json.loads(record_path.read_text(encoding='utf-8'))
    checks = {
        'manifest_sha256': sha256_bytes(manifest_path.read_bytes()) == record.get('manifest_sha256'),
        'preregistration_sha256': sha256_bytes(prereg_path.read_bytes()) == record.get('preregistration_sha256'),
    }
    if dataset_path is not None:
        checks['dataset_sha256'] = sha256_bytes(dataset_path.read_bytes()) == record.get('dataset_sha256')
    return {'valid': all(checks.values()), 'checks': checks, 'record': record}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--manifest', type=Path, required=True)
    parser.add_argument('--preregistration', type=Path, required=True)
    parser.add_argument('--out-dir', type=Path, required=True)
    parser.add_argument('--frozen-by', required=True, help='Accountable study-team role/name; not generated by the software')
    args = parser.parse_args()
    print(json.dumps(freeze(args.manifest, args.preregistration, args.out_dir, args.frozen_by), ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
