import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../../agent.html', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../../assets/css/styles.css', import.meta.url), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
assert.ok(script, 'agent inline script is required');
new Function(script);

for (const text of ['选择老人', '新对话', '已记住的信息', '要记住这件事吗', '读取依据']) assert.match(html, new RegExp(text));
for (const text of ['当前结论', '关键数据', '下一步行动', '需要帮助时', '查看依据']) assert.match(html, new RegExp(text));
for (const text of ['待处理健康事项', '今天稍后', '明早', '自选时间', '是本次复测', '哪里需要改进']) assert.match(html, new RegExp(text));
for (const text of ['选择复测时间', '不会自动保存', '确认安排', '暂不安排']) assert.match(html, new RegExp(text));
for (const text of ['做什么：', '做多久：', '如何记录：', '何时复测：', '观察指标：', '证据来源：', '停止并就医：', '确认创建干预', '确认记录']) assert.match(html, new RegExp(text));
for (const text of ['看看我的总体健康', '看看最近血压', '生成今日健康方案', '我想问一个健康问题', '今日健康贴士']) assert.ok(html.includes(text), `${text} 单入口内容缺失`);
assert.ok(!html.includes('id="mode-tabs"'), '三模式标签应彻底移除');
assert.ok(!html.includes('data-tab="plan"') && !html.includes('data-tab="qa"') && !html.includes('data-tab="tip"'), '不应保留模式切换按钮');
assert.ok(html.includes('/api/agent/daily-tip?subject_user_id='), '每日贴士接口未接入');
for (const text of ['高压（收缩压）', '低压（舒张压）', '毫米汞柱', '毫摩尔/升', '健康智能分析']) assert.ok(html.includes(text), `${text} 中文展示映射缺失`);
assert.ok(!html.includes("' · ' + llmMeta.model"), '老人端不应显示英文模型名称');
assert.ok(!html.includes('把上面的建议设为今日提醒'), '重复的今日提醒提示应移除');
for (const endpoint of ['/api/chat/conversations', '/api/agent/memories', '/api/actions/', '/regenerate']) assert.ok(html.includes(endpoint), `${endpoint} missing`);
for (const endpoint of ['/api/actions/interventions', '/executions']) assert.ok(html.includes(endpoint), `${endpoint} intervention endpoint missing`);
for (const field of ['conversation_id', 'subject_user_id', 'client_request_id']) assert.match(html, new RegExp(field));
assert.match(html, /idempotency_key/);
assert.match(html, /\/cancel/);
assert.match(css, /\.agent-context-bar/);
assert.match(css, /\.agent-memory-candidate/);
assert.match(css, /\.agent-action-preview-controls/);
assert.match(css, /\.agent-health-card/);
assert.match(css, /\.agent-health-card\.tone-urgent/);
assert.match(css, /\.agent-inbox/);
assert.match(css, /\.agent-schedule-picker/);
assert.match(css, /\.agent-schedule-options/);
assert.match(css, /\.plan-card-mini\{[\s\S]*?display:grid!important/);
assert.match(css, /\.agent-clarification-card/);
assert.match(css, /\.agent-facts\{[^}]*grid-template-columns:repeat\(3/);
assert.match(css, /font-size:18px/);
assert.match(css, /min-height:\s*48px/);
assert.ok(html.includes('id="agent-splitter"'), '左右宽度调节控件缺失');
assert.ok(html.includes('id="agent-workspace-height-resizer"'), '统一高度调节控件缺失');
assert.ok(!html.includes('id="chat-height-resizer"') && !html.includes('id="plan-height-resizer"'), '不应保留左右两套互相冲突的高度控件');
for (const text of ['工作区大小', '对话优先', '均衡布局', '辅助区优先', '高度－', '高度＋', '恢复自适应', '和小康聊一聊', '今日健康安排']) assert.ok(html.includes(text), `${text} 新工作区布局缺失`);
assert.match(html, /xiaokang-agent-split-ratio-v2/);
assert.ok(html.includes('bindAgentWorkspaceHeight'), '统一工作区高度调整未绑定');
assert.match(html, /xiaokang-agent-workspace-height-v3/);
assert.match(html, /ArrowLeft/);
assert.match(html, /ArrowRight/);
assert.match(html, /ArrowUp/);
assert.match(html, /ArrowDown/);
assert.match(css, /\.agent-height-resizer/);
assert.match(css, /cursor:row-resize/);
assert.match(css, /\.agent-layout-toolbar/);
assert.match(css, /@media\(max-width:1260px\)/);
assert.match(css, /\.agent-chat-composer/);
assert.match(css, /overflow:visible!important/);
assert.match(css, /\.agent-workspace-height-resizer/);

console.log('agent v2 frontend static acceptance: PASS');
